apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "gluster-nginxvol"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-endpoints"
    path: gvol0
    readOnly: false
  persistentVolumeReclaimPolicy: Retain

